// Source-aware architectural starters. No hardware or runtime validation is implied.
export const RDK_EXAMPLES = [
  { id: "rdk-rover", name: "RDK X5 Rover (D-Robotics)", group: "Vehicle",
    doc: { schema: 2, title: "RDK X5 Rover",
      nodes: [
        {"id":"n1","kind":"battery","x":40,"y":300,"label":"Battery","sublabel":"4S Li-ion","color":null,"addr":"","rail":"","notes":"","status":null,"flags":[]},
        {"id":"n2","kind":"regulator","x":40,"y":140,"label":"Regulator","sublabel":"5V 5A buck","color":null,"addr":"","rail":"","notes":"","status":null,"flags":[]},
        {"id":"n3","kind":"aisbc","x":330,"y":250,"label":"Robot brain","sublabel":"RDK X5","color":null,"addr":"","rail":"5V","notes":"RDK X5; regulated 5V supply sized for at least 5A. Architectural design only; hardware has not been tested.","status":null,"flags":[]},
        {"id":"n5","kind":"depthcam","x":620,"y":190,"label":"Stereo camera","sublabel":"GS130W","color":null,"addr":"","rail":"","notes":"Two CSI ribbon cables occupy both X5 camera connectors. Confirm installation and driver setup in the linked official guide.","status":null,"flags":[]},
        {"id":"n7","kind":"lidar","x":620,"y":360,"label":"LiDAR","sublabel":"RPLIDAR A1","color":null,"addr":"","rail":"5V","notes":"","status":null,"flags":[]},
        {"id":"n8","kind":"motorctl","x":200,"y":480,"label":"Motor controller","sublabel":"CAN FD ESC","color":null,"addr":"","rail":"","notes":"","status":null,"flags":[]},
        {"id":"n9","kind":"motor","x":200,"y":630,"label":"Left motor","sublabel":"BLDC","color":null,"addr":"","rail":"","notes":"","status":null,"flags":[]},
        {"id":"n10","kind":"motor","x":340,"y":630,"label":"Right motor","sublabel":"BLDC","color":null,"addr":"","rail":"","notes":"","status":null,"flags":[]},
        {"id":"n11","kind":"imu","x":330,"y":80,"label":"IMU","sublabel":"BMI088","color":null,"addr":"0x68","rail":"3.3V","notes":"","status":null,"flags":[]},
        {"id":"s1","kind":"rdksoftware","x":40,"y":820,"label":"Sensor acquisition","sublabel":"hobot_sensor","color":null,"addr":"","rail":"","notes":"Descriptive processing stage; flow arrows do not deploy or execute packages. Runtime and exact example integration require verification.","status":null,"flags":[],"fields":{"package":"hobot_sensor","target":"n3"}},
        {"id":"s2","kind":"rdksoftware","x":260,"y":820,"label":"BPU inference","sublabel":"hobot_dnn","color":null,"addr":"","rail":"","notes":"Descriptive processing stage; flow arrows do not deploy or execute packages. Runtime and exact example integration require verification.","status":null,"flags":[],"fields":{"package":"hobot_dnn","target":"n3"}},
        {"id":"s3","kind":"rdksoftware","x":480,"y":820,"label":"Image codec","sublabel":"hobot_codec","color":null,"addr":"","rail":"","notes":"Descriptive processing stage; flow arrows do not deploy or execute packages. Runtime and exact example integration require verification.","status":null,"flags":[],"fields":{"package":"hobot_codec","target":"n3"}},
        {"id":"s4","kind":"rdksoftware","x":700,"y":820,"label":"Visualization","sublabel":"hobot_render","color":null,"addr":"","rail":"","notes":"Descriptive processing stage; flow arrows do not deploy or execute packages. Runtime and exact example integration require verification.","status":null,"flags":[],"fields":{"package":"hobot_render","target":"n3"}},
      ],
      wires: [
        {"id":"w1","bus":"power","from":{"node":"n1","port":"out"},"to":{"node":"n2","port":"in"},"label":"","arrow":null,"style":null,"flow":null},
        {"id":"w2","bus":"power","from":{"node":"n2","port":"out"},"to":{"node":"n3","port":"vcc"},"label":"5V","arrow":null,"style":null,"flow":null},
        {"id":"w3","bus":"gnd","from":{"node":"n2","port":"gnd"},"to":{"node":"n3","port":"gnd"},"label":"","arrow":null,"style":null,"flow":null},
        {"id":"w4","bus":"power","from":{"node":"n1","port":"out"},"to":{"node":"n8","port":"vcc"},"label":"VBAT","arrow":null,"style":null,"flow":null},
        {"id":"w5","bus":"gnd","from":{"node":"n1","port":"gnd"},"to":{"node":"n8","port":"gnd"},"label":"","arrow":null,"style":null,"flow":null},
        {"id":"w6","bus":"mipi","from":{"node":"n3","port":"csi1"},"to":{"node":"n5","port":"csi"},"label":"CSI-2","arrow":null,"style":null,"flow":null},
        {"id":"w7","bus":"mipi","from":{"node":"n3","port":"csi2"},"to":{"node":"n5","port":"csi-right"},"label":"CSI-2","arrow":null,"style":null,"flow":null},
        {"id":"w9","bus":"uart","from":{"node":"n3","port":"uart"},"to":{"node":"n7","port":"uart"},"label":"115200","arrow":null,"style":null,"flow":null},
        {"id":"w11","bus":"canfd","from":{"node":"n3","port":"canfd"},"to":{"node":"n8","port":"canfd"},"label":"CAN FD","arrow":null,"style":null,"flow":null},
        {"id":"w12","bus":"pwm","from":{"node":"n8","port":"m1"},"to":{"node":"n9","port":"pwm"},"label":"M1","arrow":"fwd","style":null,"flow":null},
        {"id":"w13","bus":"pwm","from":{"node":"n8","port":"m2"},"to":{"node":"n10","port":"pwm"},"label":"M2","arrow":"fwd","style":null,"flow":null},
        {"id":"w14","bus":"i2c","from":{"node":"n3","port":"i2c"},"to":{"node":"n11","port":"i2c"},"label":"","arrow":null,"style":null,"flow":null},
        {"id":"sw1","bus":"flow","from":{"node":"s1","port":"out"},"to":{"node":"s2","port":"in"},"label":"logical flow","arrow":"fwd","style":null,"flow":null},
        {"id":"sw2","bus":"flow","from":{"node":"s2","port":"out"},"to":{"node":"s3","port":"in"},"label":"logical flow","arrow":"fwd","style":null,"flow":null},
        {"id":"sw3","bus":"flow","from":{"node":"s3","port":"out"},"to":{"node":"s4","port":"in"},"label":"logical flow","arrow":"fwd","style":null,"flow":null},
      ],
      zones: [
        {"id":"z1","x":24,"y":120,"w":190,"h":290,"label":"Power","color":"#f87171"},
        {"id":"z2","x":596,"y":80,"w":190,"h":400,"label":"Perception","color":"#22d3ee"},
        {"id":"z3","x":180,"y":460,"w":300,"h":280,"label":"Actuators","color":"#f472b6"},
        {"id":"zs","x":24,"y":792,"w":870,"h":150,"label":"Software on X5 · runtime not selected","color":"#a78bfa"},
      ],
      notes: [
        {"id":"t1","x":40,"y":24,"text":"Design only: stereo uses both CSI connectors. Software flow is descriptive; no runtime selected."},
        {"id":"t2","x":40,"y":970,"text":"Power detail incomplete: sensor supplies and motor returns are not drawn. General checks retain these omissions."},
      ],
      journey: [
        {"id":"j1","label":"Power and compute","view":{"cx":270,"cy":260,"zoom":1},"caption":"The 4S pack feeds a regulated 5V supply rated for at least 5A for X5. Supply and return details remain incomplete; review the general findings."},
        {"id":"j2","label":"Stereo acquisition","view":{"cx":570,"cy":260,"zoom":1.1},"caption":"GS130W left and right CSI cables occupy X5 CSI1 and CSI2. No additional MIPI camera or unverified serial-servo shortcut is drawn."},
        {"id":"j3","label":"Motion concept","view":{"cx":350,"cy":590,"zoom":1},"caption":"A conceptual CAN FD controller drives two wheels. Controller electrical interfaces, power ratings and physical CAN wiring require separate validation."},
        {"id":"j4","label":"Descriptive pipeline","view":{"cx":455,"cy":880,"zoom":1},"caption":"Sensor acquisition, inference, codec and visualization stages target X5. Flow describes intended data processing, not launch configuration; runtime is not selected."},
      ],
    },
  },
  { id: "rdk-perception", name: "RDK X5 Stereo Perception", group: "Embedded",
    doc: { schema: 2, title: "RDK X5 Stereo Perception",
      nodes: [
        {"id":"n1","kind":"battery","x":40,"y":300,"label":"Battery","sublabel":"4S Li-ion","color":null,"addr":"","rail":"","notes":"","status":null,"flags":[]},
        {"id":"n2","kind":"regulator","x":40,"y":140,"label":"Regulator","sublabel":"5V 5A buck","color":null,"addr":"","rail":"","notes":"","status":null,"flags":[]},
        {"id":"n3","kind":"aisbc","x":330,"y":250,"label":"Robot brain","sublabel":"RDK X5","color":null,"addr":"","rail":"5V","notes":"RDK X5; regulated 5V supply sized for at least 5A. Architectural design only; hardware has not been tested.","status":null,"flags":[]},
        {"id":"n5","kind":"depthcam","x":620,"y":190,"label":"Stereo camera","sublabel":"GS130W","color":null,"addr":"","rail":"","notes":"Two CSI ribbon cables occupy both X5 camera connectors. Confirm installation and driver setup in the linked official guide.","status":null,"flags":[]},
        {"id":"s1","kind":"rdksoftware","x":40,"y":520,"label":"Sensor acquisition","sublabel":"hobot_sensor","color":null,"addr":"","rail":"","notes":"Descriptive processing stage; flow arrows do not deploy or execute packages. Runtime and exact example integration require verification.","status":null,"flags":[],"fields":{"package":"hobot_sensor","target":"n3"}},
        {"id":"s2","kind":"rdksoftware","x":260,"y":520,"label":"BPU inference","sublabel":"hobot_dnn","color":null,"addr":"","rail":"","notes":"Descriptive processing stage; flow arrows do not deploy or execute packages. Runtime and exact example integration require verification.","status":null,"flags":[],"fields":{"package":"hobot_dnn","target":"n3"}},
        {"id":"s3","kind":"rdksoftware","x":480,"y":520,"label":"Image codec","sublabel":"hobot_codec","color":null,"addr":"","rail":"","notes":"Descriptive processing stage; flow arrows do not deploy or execute packages. Runtime and exact example integration require verification.","status":null,"flags":[],"fields":{"package":"hobot_codec","target":"n3"}},
        {"id":"s4","kind":"rdksoftware","x":700,"y":520,"label":"Visualization","sublabel":"hobot_render","color":null,"addr":"","rail":"","notes":"Descriptive processing stage; flow arrows do not deploy or execute packages. Runtime and exact example integration require verification.","status":null,"flags":[],"fields":{"package":"hobot_render","target":"n3"}},
      ],
      wires: [
        {"id":"w1","bus":"power","from":{"node":"n1","port":"out"},"to":{"node":"n2","port":"in"},"label":"","arrow":null,"style":null,"flow":null},
        {"id":"w2","bus":"power","from":{"node":"n2","port":"out"},"to":{"node":"n3","port":"vcc"},"label":"5V","arrow":null,"style":null,"flow":null},
        {"id":"w3","bus":"gnd","from":{"node":"n2","port":"gnd"},"to":{"node":"n3","port":"gnd"},"label":"","arrow":null,"style":null,"flow":null},
        {"id":"w6","bus":"mipi","from":{"node":"n3","port":"csi1"},"to":{"node":"n5","port":"csi"},"label":"CSI-2","arrow":null,"style":null,"flow":null},
        {"id":"w7","bus":"mipi","from":{"node":"n3","port":"csi2"},"to":{"node":"n5","port":"csi-right"},"label":"CSI-2","arrow":null,"style":null,"flow":null},
        {"id":"sw1","bus":"flow","from":{"node":"s1","port":"out"},"to":{"node":"s2","port":"in"},"label":"logical flow","arrow":"fwd","style":null,"flow":null},
        {"id":"sw2","bus":"flow","from":{"node":"s2","port":"out"},"to":{"node":"s3","port":"in"},"label":"logical flow","arrow":"fwd","style":null,"flow":null},
        {"id":"sw3","bus":"flow","from":{"node":"s3","port":"out"},"to":{"node":"s4","port":"in"},"label":"logical flow","arrow":"fwd","style":null,"flow":null},
      ],
      zones: [
        {"id":"z1","x":24,"y":120,"w":190,"h":290,"label":"Power","color":"#f87171"},
        {"id":"z2","x":596,"y":80,"w":190,"h":240,"label":"Perception","color":"#22d3ee"},
        {"id":"zs","x":24,"y":492,"w":870,"h":150,"label":"Software on X5 · runtime not selected","color":"#a78bfa"},
      ],
      notes: [
        {"id":"t1","x":40,"y":24,"text":"Design only: stereo uses both CSI connectors. Software flow is descriptive; no runtime selected."},
        {"id":"t2","x":40,"y":680,"text":"Power detail incomplete: the battery return is not drawn. General checks retain this omission; hardware has not been tested."},
      ],
      journey: [
        {"id":"j1","label":"Power and compute","view":{"cx":270,"cy":260,"zoom":1},"caption":"A conceptual 4S supply and regulated 5V 5A output feed X5. The battery return is deliberately omitted and remains a general checker finding."},
        {"id":"j2","label":"Stereo acquisition","view":{"cx":570,"cy":260,"zoom":1.1},"caption":"GS130W left and right CSI cables occupy X5 CSI1 and CSI2. No additional MIPI camera or unverified serial-servo shortcut is drawn."},
        {"id":"j4","label":"Descriptive pipeline","view":{"cx":455,"cy":580,"zoom":1},"caption":"Sensor acquisition, inference, codec and visualization stages target X5. Flow describes intended data processing, not launch configuration; runtime is not selected."},
      ],
    },
  },
  { id: "rdk-x3-robot", name: "RDK X3 Vision Robot (D-Robotics)", group: "Embedded",
    doc: { schema: 2, title: "RDK X3 Vision Robot",
      nodes: [
        {"id":"n1","kind":"battery","x":40,"y":300,"label":"Battery","sublabel":"3S Li-ion","color":null,"addr":"","rail":"","notes":"","status":null,"flags":[]},
        {"id":"n2","kind":"regulator","x":40,"y":140,"label":"Regulator","sublabel":"5V 3A buck","color":null,"addr":"","rail":"","notes":"","status":null,"flags":[]},
        {"id":"n3","kind":"aisbc","x":330,"y":250,"label":"Robot brain","sublabel":"RDK X3","color":null,"addr":"","rail":"5V","notes":"RDK X3; one MIPI CSI connector and no CAN FD, so motion control goes through a UART-linked MCU. Regulated 5V supply sized for at least 3A. Architectural design only; hardware has not been tested.","status":null,"flags":[]},
        {"id":"n4","kind":"mipicam","x":620,"y":190,"label":"Front camera","sublabel":"IMX219","color":null,"addr":"","rail":"","notes":"IMX219-family module on the single X3 CSI connector. The sensor name does not establish module, cable or driver compatibility; select the documented vendor module and adapter before ordering.","status":null,"flags":[]},
        {"id":"n5","kind":"mcu","x":200,"y":480,"label":"Drive MCU","sublabel":"Cortex-M4","color":null,"addr":"","rail":"","notes":"Takes velocity commands from X3 over UART and drives both wheels with PWM. Driver electronics and supplies are not drawn.","status":null,"flags":[]},
        {"id":"n6","kind":"motor","x":200,"y":630,"label":"Left motor","sublabel":"DC gear","color":null,"addr":"","rail":"","notes":"","status":null,"flags":[]},
        {"id":"n7","kind":"motor","x":340,"y":630,"label":"Right motor","sublabel":"DC gear","color":null,"addr":"","rail":"","notes":"","status":null,"flags":[]},
        {"id":"n8","kind":"ultrasonic","x":620,"y":360,"label":"Ultrasonic","sublabel":"HC-SR04","color":null,"addr":"","rail":"5V","notes":"","status":null,"flags":[]},
        {"id":"n9","kind":"imu","x":330,"y":80,"label":"IMU","sublabel":"MPU-6050","color":null,"addr":"0x68","rail":"3.3V","notes":"","status":null,"flags":[]},
        {"id":"s1","kind":"rdksoftware","x":40,"y":820,"label":"Sensor acquisition","sublabel":"hobot_sensor","color":null,"addr":"","rail":"","notes":"Descriptive processing stage; flow arrows do not deploy or execute packages. Runtime and exact example integration require verification.","status":null,"flags":[],"fields":{"package":"hobot_sensor","target":"n3"}},
        {"id":"s2","kind":"rdksoftware","x":260,"y":820,"label":"BPU inference","sublabel":"hobot_dnn","color":null,"addr":"","rail":"","notes":"Descriptive processing stage; flow arrows do not deploy or execute packages. Runtime and exact example integration require verification.","status":null,"flags":[],"fields":{"package":"hobot_dnn","target":"n3"}},
        {"id":"s3","kind":"rdksoftware","x":480,"y":820,"label":"Visualization","sublabel":"hobot_render","color":null,"addr":"","rail":"","notes":"Descriptive processing stage; flow arrows do not deploy or execute packages. Runtime and exact example integration require verification.","status":null,"flags":[],"fields":{"package":"hobot_render","target":"n3"}},
      ],
      wires: [
        {"id":"w1","bus":"power","from":{"node":"n1","port":"out"},"to":{"node":"n2","port":"in"},"label":"","arrow":null,"style":null,"flow":null},
        {"id":"w2","bus":"power","from":{"node":"n2","port":"out"},"to":{"node":"n3","port":"vcc"},"label":"5V","arrow":null,"style":null,"flow":null},
        {"id":"w3","bus":"gnd","from":{"node":"n2","port":"gnd"},"to":{"node":"n3","port":"gnd"},"label":"","arrow":null,"style":null,"flow":null},
        {"id":"w4","bus":"mipi","from":{"node":"n3","port":"csi1"},"to":{"node":"n4","port":"csi"},"label":"CSI-2","arrow":null,"style":null,"flow":null},
        {"id":"w5","bus":"uart","from":{"node":"n3","port":"uart"},"to":{"node":"n5","port":"uart"},"label":"115200","arrow":null,"style":null,"flow":null},
        {"id":"w6","bus":"pwm","from":{"node":"n5","port":"pwm"},"to":{"node":"n6","port":"pwm"},"label":"M1","arrow":"fwd","style":null,"flow":null},
        {"id":"w7","bus":"pwm","from":{"node":"n5","port":"pwm"},"to":{"node":"n7","port":"pwm"},"label":"M2","arrow":"fwd","style":null,"flow":null},
        {"id":"w8","bus":"gpio","from":{"node":"n3","port":"gpio"},"to":{"node":"n8","port":"trig"},"label":"TRIG","arrow":null,"style":null,"flow":null},
        {"id":"w9","bus":"gpio","from":{"node":"n3","port":"gpio"},"to":{"node":"n8","port":"echo"},"label":"ECHO","arrow":null,"style":null,"flow":null},
        {"id":"w10","bus":"i2c","from":{"node":"n3","port":"i2c"},"to":{"node":"n9","port":"i2c"},"label":"","arrow":null,"style":null,"flow":null},
        {"id":"sw1","bus":"flow","from":{"node":"s1","port":"out"},"to":{"node":"s2","port":"in"},"label":"logical flow","arrow":"fwd","style":null,"flow":null},
        {"id":"sw2","bus":"flow","from":{"node":"s2","port":"out"},"to":{"node":"s3","port":"in"},"label":"logical flow","arrow":"fwd","style":null,"flow":null},
      ],
      zones: [
        {"id":"z1","x":24,"y":120,"w":190,"h":290,"label":"Power","color":"#f87171"},
        {"id":"z2","x":596,"y":80,"w":190,"h":400,"label":"Perception","color":"#22d3ee"},
        {"id":"z3","x":180,"y":460,"w":300,"h":280,"label":"Actuators","color":"#f472b6"},
        {"id":"zs","x":24,"y":792,"w":650,"h":150,"label":"Software on X3 · runtime not selected","color":"#a78bfa"},
      ],
      notes: [
        {"id":"t1","x":40,"y":24,"text":"Design only: one CSI connector, no CAN FD; a UART MCU drives the wheels. Camera compatibility is an open finding."},
        {"id":"t2","x":40,"y":970,"text":"Power detail incomplete: MCU, sensor and motor supplies are not drawn. General checks retain these omissions; hardware has not been tested."},
      ],
      journey: [
        {"id":"j1","label":"Power and compute","view":{"cx":270,"cy":260,"zoom":1},"caption":"The 3S pack feeds a regulated 5V supply rated for at least 3A for X3. MCU, sensor and motor supplies remain undrawn; review the general findings."},
        {"id":"j2","label":"Single camera","view":{"cx":570,"cy":260,"zoom":1.1},"caption":"One IMX219-family module takes the X3's only CSI connector. The catalogue does not confirm module, cable or driver compatibility, so the checker keeps that finding open by design."},
        {"id":"j3","label":"Motion over UART","view":{"cx":320,"cy":590,"zoom":1},"caption":"The X3 has no CAN FD, so a Cortex-M4 drive MCU takes velocity commands over UART and drives both wheels with PWM. Driver electronics and returns need separate validation."},
        {"id":"j4","label":"Descriptive pipeline","view":{"cx":340,"cy":880,"zoom":1},"caption":"Sensor acquisition, inference and visualization stages target X3. Flow describes intended data processing, not launch configuration; runtime is not selected."},
      ],
    },
  },
  { id: "rdk-s100-node", name: "RDK S100 Perception Node (D-Robotics)", group: "Embedded",
    doc: { schema: 2, title: "RDK S100 Perception Node",
      nodes: [
        {"id":"n1","kind":"battery","x":40,"y":250,"label":"Battery","sublabel":"4S Li-ion","color":null,"addr":"","rail":"14.8V","notes":"Feeds the S100 directly: its documented input is 12-20V DC, so no board regulator is drawn.","status":null,"flags":[]},
        {"id":"n3","kind":"aisbc","x":330,"y":250,"label":"Perception node","sublabel":"RDK S100","color":null,"addr":"","rail":"14.8V","notes":"RDK S100 (80 TOPS, 12GB LPDDR5); 12-20V DC input from a 4S pack. Camera signals arrive through J25 and ribbon cameras need the camera expansion board. The catalogue lists no verified connector map, so every connector here is an open finding. Architectural design only; hardware has not been tested.","status":null,"flags":[]},
        {"id":"n5","kind":"depthcam","x":620,"y":190,"label":"Stereo camera","sublabel":"GS130WI","color":null,"addr":"","rail":"","notes":"Dual SC132GS global-shutter stereo module with ICM-42688-P IMU. Two ribbon cables reach the S100 through its camera expansion board; confirm installation in the linked official guide.","status":null,"flags":[]},
        {"id":"n7","kind":"lidar","x":620,"y":360,"label":"LiDAR","sublabel":"RPLIDAR C1","color":null,"addr":"","rail":"5V","notes":"","status":null,"flags":[]},
        {"id":"n8","kind":"gps","x":620,"y":520,"label":"GNSS receiver","sublabel":"RTK module","color":null,"addr":"","rail":"3.3V","notes":"","status":null,"flags":[]},
        {"id":"n9","kind":"antenna","x":800,"y":520,"label":"GNSS antenna","sublabel":"active patch","color":null,"addr":"","rail":"","notes":"","status":null,"flags":[]},
        {"id":"n12","kind":"hostpc","x":330,"y":60,"label":"Host PC","sublabel":"ROS 2 workstation","color":null,"addr":"","rail":"","notes":"","status":null,"flags":[]},
        {"id":"s1","kind":"rdksoftware","x":40,"y":820,"label":"Sensor acquisition","sublabel":"hobot_sensor","color":null,"addr":"","rail":"","notes":"Descriptive processing stage; flow arrows do not deploy or execute packages. Runtime and exact example integration require verification.","status":null,"flags":[],"fields":{"package":"hobot_sensor","target":"n3"}},
        {"id":"s2","kind":"rdksoftware","x":260,"y":820,"label":"BPU inference","sublabel":"hobot_dnn","color":null,"addr":"","rail":"","notes":"Descriptive processing stage; flow arrows do not deploy or execute packages. Runtime and exact example integration require verification.","status":null,"flags":[],"fields":{"package":"hobot_dnn","target":"n3"}},
        {"id":"s3","kind":"rdksoftware","x":480,"y":820,"label":"Image codec","sublabel":"hobot_codec","color":null,"addr":"","rail":"","notes":"Descriptive processing stage; flow arrows do not deploy or execute packages. Runtime and exact example integration require verification.","status":null,"flags":[],"fields":{"package":"hobot_codec","target":"n3"}},
        {"id":"s4","kind":"rdksoftware","x":700,"y":820,"label":"Visualization","sublabel":"hobot_render","color":null,"addr":"","rail":"","notes":"Descriptive processing stage; flow arrows do not deploy or execute packages. Runtime and exact example integration require verification.","status":null,"flags":[],"fields":{"package":"hobot_render","target":"n3"}},
      ],
      wires: [
        {"id":"w1","bus":"power","from":{"node":"n1","port":"out"},"to":{"node":"n3","port":"vcc"},"label":"14.8V","arrow":null,"style":null,"flow":null},
        {"id":"w2","bus":"gnd","from":{"node":"n1","port":"gnd"},"to":{"node":"n3","port":"gnd"},"label":"","arrow":null,"style":null,"flow":null},
        {"id":"w3","bus":"mipi","from":{"node":"n3","port":"csi1"},"to":{"node":"n5","port":"csi"},"label":"CSI-2","arrow":null,"style":null,"flow":null},
        {"id":"w4","bus":"mipi","from":{"node":"n3","port":"csi2"},"to":{"node":"n5","port":"csi-right"},"label":"CSI-2","arrow":null,"style":null,"flow":null},
        {"id":"w5","bus":"uart","from":{"node":"n3","port":"uart"},"to":{"node":"n7","port":"uart"},"label":"UART","arrow":null,"style":null,"flow":null},
        {"id":"w6","bus":"uart","from":{"node":"n3","port":"uart2"},"to":{"node":"n8","port":"uart"},"label":"NMEA","arrow":null,"style":null,"flow":null},
        {"id":"w7","bus":"rf","from":{"node":"n8","port":"ant"},"to":{"node":"n9","port":"feed"},"label":"","arrow":null,"style":null,"flow":null},
        {"id":"w8","bus":"eth","from":{"node":"n3","port":"eth"},"to":{"node":"n12","port":"eth"},"label":"1GbE","arrow":null,"style":null,"flow":null},
        {"id":"sw1","bus":"flow","from":{"node":"s1","port":"out"},"to":{"node":"s2","port":"in"},"label":"logical flow","arrow":"fwd","style":null,"flow":null},
        {"id":"sw2","bus":"flow","from":{"node":"s2","port":"out"},"to":{"node":"s3","port":"in"},"label":"logical flow","arrow":"fwd","style":null,"flow":null},
        {"id":"sw3","bus":"flow","from":{"node":"s3","port":"out"},"to":{"node":"s4","port":"in"},"label":"logical flow","arrow":"fwd","style":null,"flow":null},
      ],
      zones: [
        {"id":"z1","x":24,"y":230,"w":190,"h":140,"label":"Power","color":"#f87171"},
        {"id":"z2","x":596,"y":80,"w":190,"h":400,"label":"Perception","color":"#22d3ee"},
        {"id":"z3","x":596,"y":500,"w":340,"h":140,"label":"Positioning","color":"#60a5fa"},
        {"id":"z4","x":306,"y":40,"w":180,"h":130,"label":"Uplink","color":"#e879f9"},
        {"id":"zs","x":24,"y":792,"w":870,"h":150,"label":"Software on S100 · runtime not selected","color":"#a78bfa"},
      ],
      notes: [
        {"id":"t1","x":40,"y":24,"text":"Design only: no verified S100 connector map, so CSI, UART and Ethernet links stay open findings. Ribbon cameras need the camera expansion board."},
        {"id":"t2","x":40,"y":400,"text":"Power detail incomplete: sensor supplies and returns are not drawn. The 4S pack sits inside the S100's documented 12-20V input window; hardware has not been tested."},
      ],
      journey: [
        {"id":"j1","label":"Direct pack supply","view":{"cx":270,"cy":300,"zoom":1},"caption":"A 4S pack feeds the S100 directly because its documented input is 12 to 20V; no board regulator is needed. Sensor supplies and returns remain undrawn general findings."},
        {"id":"j2","label":"Stereo through the expansion board","view":{"cx":570,"cy":260,"zoom":1.1},"caption":"GS130WI left and right ribbons reach the S100 through its camera expansion board. The catalogue lists no verified S100 connector map, so the checker reports the pair as unverified rather than approved."},
        {"id":"j3","label":"Range and position","view":{"cx":700,"cy":480,"zoom":1},"caption":"A 2D LiDAR on UART and an RTK GNSS receiver on the second UART give range and position; the antenna feed is drawn so the RF path is not forgotten."},
        {"id":"j4","label":"Uplink and pipeline","view":{"cx":455,"cy":500,"zoom":0.8},"caption":"Ethernet carries results to a ROS 2 workstation. Acquisition, inference, codec and visualization stages target the S100; flow is descriptive and no runtime is selected."},
      ],
    },
  },
];
