// Source-aware architectural starters. No hardware or runtime validation is implied.
export const RDK_EXAMPLES = [
  { id: "rdk-rover", name: "RDK X5 Rover (D-Robotics)", group: "Vehicle",
    doc: { schema: 2, title: "RDK X5 Rover",
      nodes: [
        {"id":"n1","kind":"battery","x":40,"y":300,"label":"Battery","sublabel":"4S Li-ion","color":null,"addr":"","rail":"","notes":"","status":null,"flags":[]},
        {"id":"n2","kind":"regulator","x":40,"y":140,"label":"Regulator","sublabel":"5V 5A buck","color":null,"addr":"","rail":"","notes":"","status":null,"flags":[]},
        {"id":"n3","kind":"aisbc","x":330,"y":250,"label":"Robot brain","sublabel":"RDK X5","color":null,"addr":"","rail":"5V","notes":"RDK X5; regulated 5V supply sized for at least 5A. Architectural design only; hardware has not been tested.","status":null,"flags":[]},
        {"id":"n5","kind":"depthcam","x":620,"y":190,"label":"Stereo camera","sublabel":"GS130W","color":null,"addr":"","rail":"","notes":"Two CSI ribbon cables occupy both X5 camera connectors. Confirm installation and driver setup in the linked official guide.","status":null,"flags":[]},
        {"id":"n7","kind":"lidar","x":620,"y":360,"label":"LiDAR","sublabel":"RPLIDAR A1","color":null,"addr":"","rail":"5V","notes":"","status":null,"flags":[]},
        {"id":"n8","kind":"motorctl","x":200,"y":480,"label":"Motor controller","sublabel":"CAN FD ESC","color":null,"addr":"","rail":"","notes":"","status":null,"flags":[]},
        {"id":"n9","kind":"motor","x":200,"y":630,"label":"Left motor","sublabel":"BLDC","color":null,"addr":"","rail":"","notes":"","status":null,"flags":[]},
        {"id":"n10","kind":"motor","x":340,"y":630,"label":"Right motor","sublabel":"BLDC","color":null,"addr":"","rail":"","notes":"","status":null,"flags":[]},
        {"id":"n11","kind":"imu","x":330,"y":80,"label":"IMU","sublabel":"BMI088","color":null,"addr":"0x68","rail":"3.3V","notes":"","status":null,"flags":[]},
        {"id":"s1","kind":"rdksoftware","x":40,"y":820,"label":"Sensor acquisition","sublabel":"hobot_sensor","color":null,"addr":"","rail":"","notes":"Descriptive processing stage; flow arrows do not deploy or execute packages. Runtime and exact example integration require verification.","status":null,"flags":[],"fields":{"package":"hobot_sensor","target":"n3"}},
        {"id":"s2","kind":"rdksoftware","x":260,"y":820,"label":"BPU inference","sublabel":"hobot_dnn","color":null,"addr":"","rail":"","notes":"Descriptive processing stage; flow arrows do not deploy or execute packages. Runtime and exact example integration require verification.","status":null,"flags":[],"fields":{"package":"hobot_dnn","target":"n3"}},
        {"id":"s3","kind":"rdksoftware","x":480,"y":820,"label":"Image codec","sublabel":"hobot_codec","color":null,"addr":"","rail":"","notes":"Descriptive processing stage; flow arrows do not deploy or execute packages. Runtime and exact example integration require verification.","status":null,"flags":[],"fields":{"package":"hobot_codec","target":"n3"}},
        {"id":"s4","kind":"rdksoftware","x":700,"y":820,"label":"Visualization","sublabel":"hobot_render","color":null,"addr":"","rail":"","notes":"Descriptive processing stage; flow arrows do not deploy or execute packages. Runtime and exact example integration require verification.","status":null,"flags":[],"fields":{"package":"hobot_render","target":"n3"}},
      ],
      wires: [
        {"id":"w1","bus":"power","from":{"node":"n1","port":"out"},"to":{"node":"n2","port":"in"},"label":"","arrow":null,"style":null,"flow":null},
        {"id":"w2","bus":"power","from":{"node":"n2","port":"out"},"to":{"node":"n3","port":"vcc"},"label":"5V","arrow":null,"style":null,"flow":null},
        {"id":"w3","bus":"gnd","from":{"node":"n2","port":"gnd"},"to":{"node":"n3","port":"gnd"},"label":"","arrow":null,"style":null,"flow":null},
        {"id":"w4","bus":"power","from":{"node":"n1","port":"out"},"to":{"node":"n8","port":"vcc"},"label":"VBAT","arrow":null,"style":null,"flow":null},
        {"id":"w5","bus":"gnd","from":{"node":"n1","port":"gnd"},"to":{"node":"n8","port":"gnd"},"label":"","arrow":null,"style":null,"flow":null},
        {"id":"w6","bus":"mipi","from":{"node":"n3","port":"csi1"},"to":{"node":"n5","port":"csi"},"label":"CSI-2","arrow":null,"style":null,"flow":null},
        {"id":"w7","bus":"mipi","from":{"node":"n3","port":"csi2"},"to":{"node":"n5","port":"csi-right"},"label":"CSI-2","arrow":null,"style":null,"flow":null},
        {"id":"w9","bus":"uart","from":{"node":"n3","port":"uart"},"to":{"node":"n7","port":"uart"},"label":"115200","arrow":null,"style":null,"flow":null},
        {"id":"w11","bus":"canfd","from":{"node":"n3","port":"canfd"},"to":{"node":"n8","port":"canfd"},"label":"CAN FD","arrow":null,"style":null,"flow":null},
        {"id":"w12","bus":"pwm","from":{"node":"n8","port":"m1"},"to":{"node":"n9","port":"pwm"},"label":"M1","arrow":"fwd","style":null,"flow":null},
        {"id":"w13","bus":"pwm","from":{"node":"n8","port":"m2"},"to":{"node":"n10","port":"pwm"},"label":"M2","arrow":"fwd","style":null,"flow":null},
        {"id":"w14","bus":"i2c","from":{"node":"n3","port":"i2c"},"to":{"node":"n11","port":"i2c"},"label":"","arrow":null,"style":null,"flow":null},
        {"id":"sw1","bus":"flow","from":{"node":"s1","port":"out"},"to":{"node":"s2","port":"in"},"label":"logical flow","arrow":"fwd","style":null,"flow":null},
        {"id":"sw2","bus":"flow","from":{"node":"s2","port":"out"},"to":{"node":"s3","port":"in"},"label":"logical flow","arrow":"fwd","style":null,"flow":null},
        {"id":"sw3","bus":"flow","from":{"node":"s3","port":"out"},"to":{"node":"s4","port":"in"},"label":"logical flow","arrow":"fwd","style":null,"flow":null},
      ],
      zones: [
        {"id":"z1","x":24,"y":120,"w":190,"h":290,"label":"Power","color":"#f87171"},
        {"id":"z2","x":596,"y":80,"w":190,"h":400,"label":"Perception","color":"#22d3ee"},
        {"id":"z3","x":180,"y":460,"w":300,"h":280,"label":"Actuators","color":"#f472b6"},
        {"id":"zs","x":24,"y":792,"w":870,"h":150,"label":"Software on X5 · runtime not selected","color":"#a78bfa"},
      ],
      notes: [
        {"id":"t1","x":40,"y":24,"text":"Design only: stereo uses both CSI connectors. Software flow is descriptive; no runtime selected."},
        {"id":"t2","x":40,"y":970,"text":"Power detail incomplete: sensor supplies and motor returns are not drawn. General checks retain these omissions."},
      ],
      journey: [
        {"id":"j1","label":"Power and compute","view":{"cx":270,"cy":260,"zoom":1},"caption":"The 4S pack feeds a regulated 5V supply rated for at least 5A for X5. Supply and return details remain incomplete; review the general findings."},
        {"id":"j2","label":"Stereo acquisition","view":{"cx":570,"cy":260,"zoom":1.1},"caption":"GS130W left and right CSI cables occupy X5 CSI1 and CSI2. No additional MIPI camera or unverified serial-servo shortcut is drawn."},
        {"id":"j3","label":"Motion concept","view":{"cx":350,"cy":590,"zoom":1},"caption":"A conceptual CAN FD controller drives two wheels. Controller electrical interfaces, power ratings and physical CAN wiring require separate validation."},
        {"id":"j4","label":"Descriptive pipeline","view":{"cx":455,"cy":880,"zoom":1},"caption":"Sensor acquisition, inference, codec and visualization stages target X5. Flow describes intended data processing, not launch configuration; runtime is not selected."},
      ],
    },
  },
  { id: "rdk-perception", name: "RDK X5 Stereo Perception", group: "Embedded",
    doc: { schema: 2, title: "RDK X5 Stereo Perception",
      nodes: [
        {"id":"n1","kind":"battery","x":40,"y":300,"label":"Battery","sublabel":"4S Li-ion","color":null,"addr":"","rail":"","notes":"","status":null,"flags":[]},
        {"id":"n2","kind":"regulator","x":40,"y":140,"label":"Regulator","sublabel":"5V 5A buck","color":null,"addr":"","rail":"","notes":"","status":null,"flags":[]},
        {"id":"n3","kind":"aisbc","x":330,"y":250,"label":"Robot brain","sublabel":"RDK X5","color":null,"addr":"","rail":"5V","notes":"RDK X5; regulated 5V supply sized for at least 5A. Architectural design only; hardware has not been tested.","status":null,"flags":[]},
        {"id":"n5","kind":"depthcam","x":620,"y":190,"label":"Stereo camera","sublabel":"GS130W","color":null,"addr":"","rail":"","notes":"Two CSI ribbon cables occupy both X5 camera connectors. Confirm installation and driver setup in the linked official guide.","status":null,"flags":[]},
        {"id":"s1","kind":"rdksoftware","x":40,"y":520,"label":"Sensor acquisition","sublabel":"hobot_sensor","color":null,"addr":"","rail":"","notes":"Descriptive processing stage; flow arrows do not deploy or execute packages. Runtime and exact example integration require verification.","status":null,"flags":[],"fields":{"package":"hobot_sensor","target":"n3"}},
        {"id":"s2","kind":"rdksoftware","x":260,"y":520,"label":"BPU inference","sublabel":"hobot_dnn","color":null,"addr":"","rail":"","notes":"Descriptive processing stage; flow arrows do not deploy or execute packages. Runtime and exact example integration require verification.","status":null,"flags":[],"fields":{"package":"hobot_dnn","target":"n3"}},
        {"id":"s3","kind":"rdksoftware","x":480,"y":520,"label":"Image codec","sublabel":"hobot_codec","color":null,"addr":"","rail":"","notes":"Descriptive processing stage; flow arrows do not deploy or execute packages. Runtime and exact example integration require verification.","status":null,"flags":[],"fields":{"package":"hobot_codec","target":"n3"}},
        {"id":"s4","kind":"rdksoftware","x":700,"y":520,"label":"Visualization","sublabel":"hobot_render","color":null,"addr":"","rail":"","notes":"Descriptive processing stage; flow arrows do not deploy or execute packages. Runtime and exact example integration require verification.","status":null,"flags":[],"fields":{"package":"hobot_render","target":"n3"}},
      ],
      wires: [
        {"id":"w1","bus":"power","from":{"node":"n1","port":"out"},"to":{"node":"n2","port":"in"},"label":"","arrow":null,"style":null,"flow":null},
        {"id":"w2","bus":"power","from":{"node":"n2","port":"out"},"to":{"node":"n3","port":"vcc"},"label":"5V","arrow":null,"style":null,"flow":null},
        {"id":"w3","bus":"gnd","from":{"node":"n2","port":"gnd"},"to":{"node":"n3","port":"gnd"},"label":"","arrow":null,"style":null,"flow":null},
        {"id":"w6","bus":"mipi","from":{"node":"n3","port":"csi1"},"to":{"node":"n5","port":"csi"},"label":"CSI-2","arrow":null,"style":null,"flow":null},
        {"id":"w7","bus":"mipi","from":{"node":"n3","port":"csi2"},"to":{"node":"n5","port":"csi-right"},"label":"CSI-2","arrow":null,"style":null,"flow":null},
        {"id":"sw1","bus":"flow","from":{"node":"s1","port":"out"},"to":{"node":"s2","port":"in"},"label":"logical flow","arrow":"fwd","style":null,"flow":null},
        {"id":"sw2","bus":"flow","from":{"node":"s2","port":"out"},"to":{"node":"s3","port":"in"},"label":"logical flow","arrow":"fwd","style":null,"flow":null},
        {"id":"sw3","bus":"flow","from":{"node":"s3","port":"out"},"to":{"node":"s4","port":"in"},"label":"logical flow","arrow":"fwd","style":null,"flow":null},
      ],
      zones: [
        {"id":"z1","x":24,"y":120,"w":190,"h":290,"label":"Power","color":"#f87171"},
        {"id":"z2","x":596,"y":80,"w":190,"h":240,"label":"Perception","color":"#22d3ee"},
        {"id":"zs","x":24,"y":492,"w":870,"h":150,"label":"Software on X5 · runtime not selected","color":"#a78bfa"},
      ],
      notes: [
        {"id":"t1","x":40,"y":24,"text":"Design only: stereo uses both CSI connectors. Software flow is descriptive; no runtime selected."},
        {"id":"t2","x":40,"y":680,"text":"Power detail incomplete: the battery return is not drawn. General checks retain this omission; hardware has not been tested."},
      ],
      journey: [
        {"id":"j1","label":"Power and compute","view":{"cx":270,"cy":260,"zoom":1},"caption":"A conceptual 4S supply and regulated 5V 5A output feed X5. The battery return is deliberately omitted and remains a general checker finding."},
        {"id":"j2","label":"Stereo acquisition","view":{"cx":570,"cy":260,"zoom":1.1},"caption":"GS130W left and right CSI cables occupy X5 CSI1 and CSI2. No additional MIPI camera or unverified serial-servo shortcut is drawn."},
        {"id":"j4","label":"Descriptive pipeline","view":{"cx":455,"cy":580,"zoom":1},"caption":"Sensor acquisition, inference, codec and visualization stages target X5. Flow describes intended data processing, not launch configuration; runtime is not selected."},
      ],
    },
  },
];
